global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'my-project'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'octoprint'
    scrape_interval: 5s
    metrics_path: '/plugin/prometheus_exporter/metrics'
    static_configs:
      - targets: ['octoprint:80'] # this will only work if your octoprint instance is hosted from the compose file

